DROP TABLE EMPLOYEE_AUTH;
DROP TABLE EMPLOYEE;
DROP TABLE BK_FUNCTION;

CREATE TABLE EMPLOYEE (
EMP_NO VARCHAR2(10) NOT NULL,
ID VARCHAR2(40) NOT NULL,
PASSWORD VARCHAR2(40) NOT NULL,
NAME VARCHAR2(40) NOT NULL,
LASTLOGIN TIMESTAMP,
LASTBADLOGIN TIMESTAMP,
BADLOGINTRY NUMBER(10),
PHOTO BLOB,
STATE VARCHAR2(10) NOT NULL,
CREATEDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
CONSTRAINT EMP_NO_PK PRIMARY KEY(EMP_NO));

DROP SEQUENCE EMP_SEQ;

CREATE SEQUENCE EMP_SEQ
INCREMENT BY 1 
START WITH 1 
NOCACHE;

------insert先寫在這裡-------

INSERT INTO EMPLOYEE(EMP_NO, ID, PASSWORD, NAME, STATE) VALUES('EM'||(LPAD(to_char
(EMP_SEQ.NEXTVAL),8,'0')), 'peter@forhouse.com', '123456' ,'吳神', 'Active');
INSERT INTO EMPLOYEE(EMP_NO, ID, PASSWORD, NAME, STATE) VALUES('EM'||(LPAD(to_char
(EMP_SEQ.NEXTVAL),8,'0')), 'yyy@forhouse.com', '123456' ,'楊宇茵', 'Active');
INSERT INTO EMPLOYEE(EMP_NO, ID, PASSWORD, NAME, STATE) VALUES('EM'||(LPAD(to_char
(EMP_SEQ.NEXTVAL),8,'0')), 'dragon@forhouse.com', '123456' ,'趙子龍', 'Active');
------------------------------
CREATE TABLE BK_FUNCTION(
FUNCTION_NO NUMBER(10),
NAME VARCHAR2(40) NOT NULL, 
DESCRIBE VARCHAR2(100) NOT NULL, 
STATE VARCHAR2(10) NOT NULL,
UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
CONSTRAINT FUNCTION_NO_PK PRIMARY KEY(FUNCTION_NO));

DROP SEQUENCE BK_FUNCTION_NO;

CREATE SEQUENCE BK_FUNCTION_NO
INCREMENT BY 1 
START WITH 100 
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO BK_FUNCTION(FUNCTION_NO, NAME, DESCRIBE, STATE) 
VALUES(BK_FUNCTION_NO.NEXTVAL, '管理員工', '管理後台帳號、管理後台帳號權限' ,'On');
INSERT INTO BK_FUNCTION(FUNCTION_NO, NAME, DESCRIBE, STATE) 
VALUES(BK_FUNCTION_NO.NEXTVAL, '審核權限', '審核房仲註冊、審核廠商註冊' ,'On');
INSERT INTO BK_FUNCTION(FUNCTION_NO, NAME, DESCRIBE, STATE) 
VALUES(BK_FUNCTION_NO.NEXTVAL, '維護房屋資料', '房屋資料更新檢視、房屋資料爬蟲開關' ,'Test');
INSERT INTO BK_FUNCTION(FUNCTION_NO, NAME, DESCRIBE, STATE) 
VALUES(BK_FUNCTION_NO.NEXTVAL, '管理檢舉', '審核檢舉房仲、審核檢舉廠商' ,'On');
INSERT INTO BK_FUNCTION(FUNCTION_NO, NAME, DESCRIBE, STATE) 
VALUES(BK_FUNCTION_NO.NEXTVAL, '管理News', '管理房市最新消息、管理系統公告、管理促銷資訊' ,'On');
INSERT INTO BK_FUNCTION(FUNCTION_NO, NAME, DESCRIBE, STATE) 
VALUES(BK_FUNCTION_NO.NEXTVAL, '管理廣告', '審核廠商廣告申請刊登廣告撤銷廣告' ,'On');
INSERT INTO BK_FUNCTION(FUNCTION_NO, NAME, DESCRIBE, STATE) 
VALUES(BK_FUNCTION_NO.NEXTVAL, '管理常見問題', '更新問題' ,'On');



--xxxxxxxxxx----------------------
CREATE TABLE EMPLOYEE_AUTH(
EMP_NO VARCHAR2(10) NOT NULL,
FUNCTION_NO NUMBER(10) NOT NULL,
TIMESTAMP  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
EDITOR VARCHAR2(10),
CONSTRAINT EMP_NO_FK FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEE(EMP_NO),
CONSTRAINT FUNCTION_NO_FK FOREIGN KEY (FUNCTION_NO) REFERENCES BK_FUNCTION
(FUNCTION_NO),
CONSTRAINT EMPLOYEE_AUTH_PK PRIMARY KEY(EMP_NO,FUNCTION_NO));

--xxxxxxxxxx-----------------------




DROP TABLE PRODUCT_ORDER;
CREATE TABLE PRODUCT_ORDER(
ORDER_NO VARCHAR2(10) NOT NULL, 
MEM_NO VARCHAR2(10) NOT NULL,
SLR_NO VARCHAR2(10) NOT NULL,
ORDER_STATUS VARCHAR2(20),
RESR_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
SELLER_RATE NUMBER(2),
MEMBER_RATE NUMBER(2),
MEMBER_REVIEW VARCHAR2(100),
PARAMS CLOB,
CP_NO VARCHAR2(10),
CONSTRAINT ORDER_NO_PK PRIMARY KEY(ORDER_NO),
CONSTRAINT MEM_NO_FK FOREIGN KEY (Mem_NO) REFERENCES Member(Mem_NO),
CONSTRAINT SLR_NO FOREIGN KEY (SLR_NO) REFERENCES Seller(SLR_NO));

DROP SEQUENCE ORDER_NO_SEQ;

CREATE SEQUENCE ORDER_NO_SEQ
INCREMENT BY 1 
START WITH 1 
NOMAXVALUE
NOCYCLE
NOCACHE;

INSERT INTO PRODUCT_ORDER(ORDER_NO, MEM_NO, SLR_NO, Order_Status) 
VALUES('OD'||(LPAD(to_char(EMP_SEQ.NEXTVAL),8,'0')), 'MB00000001', 'SL00000001' ,'order');
INSERT INTO PRODUCT_ORDER(ORDER_NO, MEM_NO, SLR_NO, Order_Status) 
VALUES('OD'||(LPAD(to_char(EMP_SEQ.NEXTVAL),8,'0')), 'MB00000001', 'SL00000001' ,'order');
INSERT INTO PRODUCT_ORDER(ORDER_NO, MEM_NO, SLR_NO, Order_Status) 
VALUES('OD'||(LPAD(to_char(EMP_SEQ.NEXTVAL),8,'0')), 'MB00000002', 'SL00000001' ,'order');
INSERT INTO PRODUCT_ORDER(ORDER_NO, MEM_NO, SLR_NO, Order_Status) 
VALUES('OD'||(LPAD(to_char(EMP_SEQ.NEXTVAL),8,'0')), 'MB00000002', 'SL00000002' ,'order');
INSERT INTO PRODUCT_ORDER(ORDER_NO, MEM_NO, SLR_NO, Order_Status) 
VALUES('OD'||(LPAD(to_char(EMP_SEQ.NEXTVAL),8,'0')), 'MB00000003', 'SL00000003' ,'order');
INSERT INTO PRODUCT_ORDER(ORDER_NO, MEM_NO, SLR_NO, Order_Status) 
VALUES('OD'||(LPAD(to_char(EMP_SEQ.NEXTVAL),8,'0')), 'MB00000004', 'SL00000003' ,'deliver');
INSERT INTO PRODUCT_ORDER(ORDER_NO, MEM_NO, SLR_NO, Order_Status) 
VALUES('OD'||(LPAD(to_char(EMP_SEQ.NEXTVAL),8,'0')), 'MB00000004', 'SL00000004' ,'cancel');
-------------------------------------------------------------

DROP TABLE Order_Detail;
CREATE TABLE Order_Detail(
Order_No VARCHAR2(10) NOT NULL,
PRD_NO VARCHAR2(10) NOT NULL,
Unit_price NUMBER(10),
quantity NUMBER(10)
);




----------------------------------

